baseURL = "https://bugswithblas.com/"
languageCode = "en"
theme = "adritian-free-hugo-theme"

[params]

  title = 'Bugs with Blas'
  description = 'Bugs with Blas'
  images = ['/img/og-img.png']
  sections = ["showcase", "experience"]
  # sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  homepageExperienceCount = 6

  [params.analytics]
  vercelPageInsights = false
  vercelAnalytics = false
  
  [params.analytics.googleAnalytics]
      code = "G-R3M6L1SYWE"
      enabled = true
  [params.analytics.googleTagManager]
      code = "GTM-W7D949VG"
      enabled = true

[build]
  [build.buildStats]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = true

[params.languages.selector.disable]
  footer = true

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    title = ''
    weight = 0

    [languages.en.menus]


      [[languages.en.menus.header]]
        name = "Blog"
        URL = "/blog"
        weight = 2

      [[languages.en.menus.footer]]
        name = "Blog"
        URL = "/blog"
        weight = 2

  
  

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/custom.css"
  [[params.plugins.css]]
  URL = "css/adritian-icons.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"

  # SCSS Plugins
  [[params.plugins.scss]]
  URL = "scss/adritian.scss"


# theme/color style 
[params.colorTheme]

## the following configuration would disable automatic theme selection
#  [params.colorTheme.auto]
#    disable = true
#  [params.colorTheme.forced]
#    theme = "dark"

## the following parameter will disable theme override in the footer
#  [params.colorTheme.selector.disable]
#  footer = true


## by default we allow override AND automatic selection

[params.blog]
layout = "sidebar" # options: default, sidebar
sidebarWidth = "20" # percentage width of the sidebar
showCategories = false
showRecentPosts = true
recentPostCount = 5
listStyle = "simple" # options: simple, summary
